# Author: Clint J Edwards  <clint.j.edwards@gmail.com>

"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base0B"
"variable.other.member" = "base0B"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
base00 = "#424242" # Default Background
base01 = "#4a4a4a" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#74b9ff" # Selection Background
base03 = "#807d78" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#d3d0c8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#d3d0c8" # Light Foreground (Not often used)
base07 = "#4a4a4a" # Light Background (Not often used)
base08 = "#ff7675" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#f0ba8f" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#ffeaa7" # Classes, Markup Bold, Search Text Background
base0B = "#badc58" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#ffeaa7" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#74b9ff" # Functions, Methods, Attribute IDs, Headings
base0E = "#cc99cc" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#d65d0e" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>