# These are settings for helix-ext which adds some much needed features left out by the original helix in favor
# of plugins. Namely a file-tree. And the ability to move selections.
theme = "eastwood"

[editor]
rulers = [120]
color-modes = true
text-width = 120
true-color = true
insert-final-newline = true
line-number = "relative"
auto-pairs = false
end-of-line-diagnostics = "hint"
auto-completion = false # ctrl+space to force
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.smart-tab]
enable = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.indent-guides]
render = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.inline-diagnostics]
cursor-line  = "hint"

[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]
esc = ["collapse_selection", "normal_mode"]
C-v = [":clipboard-paste-before"]
C-space = ["completion"]

[keys.normal]
Z = { Z = ":wq" }
C-s = [":w"]
"#" = "toggle_comments"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
X = ["extend_line_up", "extend_to_line_bounds"]

# Put rainbow-brackets and indent-guides in here once https://github.com/helix-editor/helix/issues/8853 merges
C-space = [":toggle lsp.display-inlay-hints", ":toggle rainbow-brackets", ":toggle indent-guides.render"]

esc = ["collapse_selection", "keep_primary_selection"]
C-v = [":clipboard-paste-before"]
y = ["yank", "yank_to_clipboard"]
C-r = [
    ":write-all",
    ":insert-output scooter >/dev/tty",
    ":redraw",
    ":reload-all"
]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

[keys.normal.space]
# Allow me to get github permalinks from my code.
G = ":run-shell-command git-permalink \"%{buffer_name}:%{selection_line_start}-%{selection_line_end}\" | xclip -selection clipboard"
l = ":reflow"
