# These are settings for helix-ext which adds some much needed features left out by the original helix in favor
# of plugins. Namely a file-tree. And the ability to move selections.
theme = "eastwood"

[editor]
rulers = [120]
color-modes = true
text-width = 120
true-color = true
insert-final-newline = true
line-number = "relative"
auto-pairs = false
end-of-line-diagnostics = "hint"
auto-completion = false # ctrl+x to force

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.smart-tab]
enable = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.indent-guides]
render = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.inline-diagnostics]
cursor-line  = "hint"

[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]
esc = ["collapse_selection", "normal_mode"]
C-v = [":clipboard-paste-before"]
C-space = ["completion"]

[keys.normal]
C-s = [":w"]
X = ["extend_line_up", "extend_to_line_bounds"]
C-space = [":toggle lsp.display-inlay-hints"]#, ":toggle rainbow-brackets", ":toggle indent-guides.render"]
# Put rainbow-brackets and indent-guides in here once https://github.com/helix-editor/helix/issues/8853 merges
esc = ["collapse_selection", "keep_primary_selection"]
C-v = [":clipboard-paste-before"]
y = ["yank", "yank_to_clipboard"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# Use yazi to perform file explorer duties.
[keys.normal.space]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
E = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-u41ae14",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
