# Language settings

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = ["gopls"]

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman", "mpls"]

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"

# LSP Settings
[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
local = "goimports"
semanticTokens = true
staticcheck = true
verboseOutput = true
usePlaceholders = true
completeUnimported = true

[language-server.gopls.config.analyses]
fieldalignment = false
nilness = true
unusedparams = true
unusedwrite = true
useany = true

[language-server.gopls.config.hints]
assignVariableType = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.mpls]
command = "mpls"
args = ["--dark-mode", "--enable-emoji"]
