# Author: Clint J Edwards  <clint.j.edwards@gmail.com>

"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base0A", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.virtual" = "base03"
"ui.virtual.ruler" = {bg = "base01"} 
"ui.text.focus" = "base05"
"variable" = "base05"
"variable.other.member" = "base0D"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base0B"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base05"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base05"
"ui.help" = { fg = "base06", bg = "base01" }
"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
base00 = "#424242" # Default Background (Gray)
base01 = "#4a4a4a" # Lighter Gray (Lighter Background)
base02 = "#74b9ff" # Light Blue
base03 = "#807d78" # Even Lighter Gray (Comments, Invisibles, Line Highlighting)
base04 = "#b8b8b8" # Very Light Gray (Dark Foreground (Used for status bars))
base05 = "#d3d0c8" # Even Ligher Gray (Default Foreground)
base06 = "#d3d0c8" # Same as above.
base07 = "#4a4a4a" # Same as base01.
base08 = "#ff7675" # Pastel Red
base09 = "#f0ba8f" # Pastel Orange
base0A = "#ffeaa7" # Pastel Yellow
base0B = "#badc58" # Pastel Green
base0C = "#ffeaa7" # Pastel Yellow
base0D = "#a7c7e7" # Pastel Blue
base0E = "#cc99cc" # Pastel Magenta
base0F = "#d65d0e" # Strong Orange
