theme = "eastwood"

[editor]
rulers = [120]
color-modes = true
text-width = 120
true-color = true
insert-file-newline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
C-s = [":w"]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
C-space = [":toggle lsp.display-inlay-hints"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
